// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Templify.Persistence.Contexts;

#nullable disable

namespace Templify.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250823144005_AddUserDescription")]
    partial class AddUserDescription
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Templify.Domain.Entities.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Avatar")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("IdentityId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("IdentityId")
                        .IsUnique();

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("Templify.Domain.Entities.ApplicationRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Администратор системы",
                            IsActive = true,
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "2",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Обычный пользователь",
                            IsActive = true,
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Templify.Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("Avatar")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Templify.Domain.Entities.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SocialLinks")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("TotalDownloads")
                        .HasColumnType("integer");

                    b.Property<int>("TotalProducts")
                        .HasColumnType("integer");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvatarUrl = "~/src/img/person1.jpg",
                            Bio = "Award-winning design studio specializing in modern web templates and digital experiences. With over 10 years of experience, we create stunning, user-friendly designs that help businesses stand out in the digital landscape.",
                            Email = "hello@designvista.com",
                            Name = "DesignVista",
                            SocialLinks = "{\"twitter\":\"@designvista\",\"linkedin\":\"designvista\",\"dribbble\":\"designvista\"}",
                            Specialization = "Web Design & UI/UX",
                            TotalDownloads = 15800,
                            TotalProducts = 8,
                            Website = "https://designvista.com"
                        },
                        new
                        {
                            Id = 2,
                            AvatarUrl = "~/src/img/person2.jpg",
                            Bio = "Creative agency focused on delivering exceptional digital solutions. Our team of passionate designers and developers work together to create templates that combine beauty with functionality.",
                            Email = "contact@designcraft.com",
                            Name = "DesignCraft",
                            SocialLinks = "{\"twitter\":\"@designcraft\",\"linkedin\":\"designcraft\",\"behance\":\"designcraft\"}",
                            Specialization = "Creative Design & Branding",
                            TotalDownloads = 12400,
                            TotalProducts = 6,
                            Website = "https://designcraft.com"
                        },
                        new
                        {
                            Id = 3,
                            AvatarUrl = "~/src/img/person3.jpg",
                            Bio = "Full-stack development studio with expertise in modern web technologies. We specialize in creating robust, scalable templates that developers love to work with.",
                            Email = "hello@codemaven.com",
                            Name = "CodeMaven",
                            SocialLinks = "{\"twitter\":\"@codemaven\",\"github\":\"codemaven\",\"linkedin\":\"codemaven\"}",
                            Specialization = "Web Development & 3D",
                            TotalDownloads = 9800,
                            TotalProducts = 5,
                            Website = "https://codemaven.com"
                        },
                        new
                        {
                            Id = 4,
                            AvatarUrl = "~/src/img/person4.jpg",
                            Bio = "Experienced web developer and designer with a passion for creating intuitive user experiences. Specializing in responsive design and modern web standards.",
                            Email = "contact@webmaster.com",
                            Name = "WebMaster",
                            SocialLinks = "{\"twitter\":\"@webmaster\",\"linkedin\":\"webmaster\",\"codepen\":\"webmaster\"}",
                            Specialization = "Frontend Development",
                            TotalDownloads = 7200,
                            TotalProducts = 4,
                            Website = "https://webmaster.com"
                        },
                        new
                        {
                            Id = 5,
                            AvatarUrl = "~/src/img/person5.jpg",
                            Bio = "Premium theme development studio creating high-quality templates for businesses worldwide. Our focus is on performance, accessibility, and user experience.",
                            Email = "hello@themewiz.com",
                            Name = "ThemeWiz",
                            SocialLinks = "{\"twitter\":\"@themewiz\",\"linkedin\":\"themewiz\",\"dribbble\":\"themewiz\"}",
                            Specialization = "Premium Themes & SaaS",
                            TotalDownloads = 13500,
                            TotalProducts = 7,
                            Website = "https://themewiz.com"
                        },
                        new
                        {
                            Id = 6,
                            AvatarUrl = "~/src/img/person6.jpg",
                            Bio = "Creative design studio pushing the boundaries of digital design. We create unique, innovative templates that inspire and engage users across all platforms.",
                            Email = "contact@pixelgenius.com",
                            Name = "PixelGenius",
                            SocialLinks = "{\"twitter\":\"@pixelgenius\",\"behance\":\"pixelgenius\",\"instagram\":\"pixelgenius\"}",
                            Specialization = "Creative Design & Animation",
                            TotalDownloads = 16800,
                            TotalProducts = 9,
                            Website = "https://pixelgenius.com"
                        },
                        new
                        {
                            Id = 7,
                            AvatarUrl = "~/src/img/person1.jpg",
                            Bio = "Professional web development agency specializing in custom solutions and premium templates. We help businesses establish a strong online presence.",
                            Email = "hello@webmajestic.com",
                            Name = "WebMajestic",
                            SocialLinks = "{\"twitter\":\"@webmajestic\",\"linkedin\":\"webmajestic\",\"github\":\"webmajestic\"}",
                            Specialization = "Web Development & Agency",
                            TotalDownloads = 11200,
                            TotalProducts = 6,
                            Website = "https://webmajestic.com"
                        },
                        new
                        {
                            Id = 8,
                            AvatarUrl = "~/src/img/person2.jpg",
                            Bio = "Leading template marketplace with a focus on quality and innovation. Our team creates templates that help businesses grow and succeed online.",
                            Email = "contact@templatepro.com",
                            Name = "TemplatePro",
                            SocialLinks = "{\"twitter\":\"@templatepro\",\"linkedin\":\"templatepro\",\"dribbble\":\"templatepro\"}",
                            Specialization = "Template Development",
                            TotalDownloads = 22400,
                            TotalProducts = 12,
                            Website = "https://templatepro.com"
                        },
                        new
                        {
                            Id = 9,
                            AvatarUrl = "~/src/img/person3.jpg",
                            Bio = "Modern web studio creating cutting-edge digital experiences. We combine creativity with technology to deliver exceptional results for our clients.",
                            Email = "hello@webstudio.com",
                            Name = "WebStudio",
                            SocialLinks = "{\"twitter\":\"@webstudio\",\"linkedin\":\"webstudio\",\"behance\":\"webstudio\"}",
                            Specialization = "Modern Web Development",
                            TotalDownloads = 8900,
                            TotalProducts = 5,
                            Website = "https://webstudio.com"
                        });
                });

            modelBuilder.Entity("Templify.Domain.Entities.AuthorSub", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AuthorSubs");
                });

            modelBuilder.Entity("Templify.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("AuthorId")
                        .HasColumnType("integer");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("CategoryType")
                        .HasColumnType("integer");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("Downloads")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("Tags")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "DesignVista",
                            AuthorId = 1,
                            Category = "Business",
                            CategoryType = 1,
                            Description = "Professional Business Platform designed for modern enterprises seeking a comprehensive digital presence. This premium template features a sophisticated design with advanced functionality for corporate management, client relations, and business operations. Built with the latest web technologies, it offers seamless integration capabilities and responsive design that adapts perfectly to all devices. The platform includes built-in analytics, project management tools, and customer relationship management features to streamline your business processes.",
                            Downloads = 4580,
                            ImageUrl = "~/src/img/tem1.png",
                            Name = "BusinessPro",
                            Price = 99m,
                            Tags = "business, professional, platform"
                        },
                        new
                        {
                            Id = 2,
                            Author = "DesignCraft",
                            AuthorId = 2,
                            Category = "Business",
                            CategoryType = 1,
                            Description = "Corporate Management System that revolutionizes how businesses handle their daily operations and team collaboration. This enterprise-grade template provides a centralized hub for managing projects, tracking performance metrics, and facilitating communication across departments. The intuitive interface makes it easy for teams to collaborate effectively while maintaining professional standards and brand consistency. With advanced security features and customizable workflows, CorporateHub ensures your business data remains protected while optimizing productivity.",
                            Downloads = 3580,
                            ImageUrl = "~/src/img/tem2.png",
                            Name = "CorporateHub",
                            Price = 89m,
                            Tags = "corporate, management, system"
                        },
                        new
                        {
                            Id = 3,
                            Author = "CodeMaven",
                            AuthorId = 3,
                            Category = "3D Web",
                            CategoryType = 2,
                            Description = "3D Web Design Platform that brings your digital projects to life with stunning three-dimensional graphics and interactive elements. This cutting-edge template leverages modern WebGL technology to create immersive user experiences that captivate visitors and enhance engagement. Perfect for creative agencies, design studios, and innovative brands looking to showcase their work in a visually striking manner. The platform includes customizable 3D models, animation libraries, and performance optimization tools to ensure smooth rendering across all devices.",
                            Downloads = 2980,
                            ImageUrl = "~/src/img/tem3.png",
                            Name = "3DWebStudio",
                            Price = 129m,
                            Tags = "3d, web, design"
                        },
                        new
                        {
                            Id = 4,
                            Author = "WebMaster",
                            AuthorId = 4,
                            Category = "3D Web",
                            CategoryType = 2,
                            Description = "3D Interactive Experience that transforms ordinary websites into extraordinary digital journeys through immersive three-dimensional environments. This revolutionary template combines advanced 3D rendering with intuitive user interfaces to create memorable brand experiences that leave lasting impressions. Built for performance and accessibility, it ensures smooth navigation and fast loading times while delivering stunning visual effects. Ideal for gaming companies, entertainment platforms, and forward-thinking brands who want to push the boundaries of web design.",
                            Downloads = 2504,
                            ImageUrl = "~/src/img/tem4.png",
                            Name = "ThreeDimensional",
                            Price = 149m,
                            Tags = "3d, interactive, experience"
                        },
                        new
                        {
                            Id = 5,
                            Author = "ThemeWiz",
                            AuthorId = 5,
                            Category = "Saas Platforms",
                            CategoryType = 3,
                            Description = "Cloud-based SaaS Platform that provides a scalable foundation for software-as-a-service applications with enterprise-grade reliability and performance. This comprehensive template includes user authentication, subscription management, and analytics dashboards to help you build and grow your SaaS business efficiently. The modular architecture allows for easy customization and integration with third-party services, while the responsive design ensures optimal user experience across all devices. Built with security best practices and cloud-native technologies for maximum scalability and reliability.",
                            Downloads = 1805,
                            ImageUrl = "~/src/img/tem5.png",
                            Name = "CloudSaaS",
                            Price = 199m,
                            Tags = "saas, cloud, platform"
                        },
                        new
                        {
                            Id = 6,
                            Author = "PixelGenius",
                            AuthorId = 6,
                            Category = "Saas Platforms",
                            CategoryType = 3,
                            Description = "Professional SaaS Solution designed to accelerate your software business with a complete toolkit for subscription management and user engagement. This feature-rich template includes advanced billing systems, user onboarding flows, and comprehensive analytics to help you understand and optimize your customer journey. The clean, modern interface focuses on user experience while providing powerful backend capabilities for managing complex SaaS operations. With built-in A/B testing tools and conversion optimization features, SaaSPro helps you maximize your revenue potential.",
                            Downloads = 1506,
                            ImageUrl = "~/src/img/tem6.png",
                            Name = "SaaSPro",
                            Price = 179m,
                            Tags = "saas, professional, solution"
                        },
                        new
                        {
                            Id = 7,
                            Author = "WebMajestic",
                            AuthorId = 7,
                            Category = "Agency",
                            CategoryType = 4,
                            Description = "Digital Agency Platform that showcases your creative work and attracts new clients with a professional, portfolio-focused design. This comprehensive template includes project galleries, client testimonials, and service showcases to highlight your agency's capabilities and past successes. The integrated contact forms and lead generation tools help convert visitors into clients, while the blog and content management features allow you to establish thought leadership in your industry. Built for creative agencies, marketing firms, and design studios who want to make a lasting impression.",
                            Downloads = 1200,
                            ImageUrl = "~/src/img/tem7.png",
                            Name = "AgencyHub",
                            Price = 159m,
                            Tags = "agency, digital, platform"
                        },
                        new
                        {
                            Id = 8,
                            Author = "TemplatePro",
                            AuthorId = 8,
                            Category = "Agency",
                            CategoryType = 4,
                            Description = "Creative Agency Website that reflects the innovative spirit and artistic vision of modern creative businesses. This visually stunning template combines bold typography, dynamic layouts, and interactive elements to create a memorable brand experience that sets your agency apart from the competition. The portfolio section showcases your best work with elegant galleries and case studies, while the team profiles and about sections help build trust and credibility with potential clients. Perfect for advertising agencies, design studios, and creative consultancies looking to make a bold statement.",
                            Downloads = 1100,
                            ImageUrl = "~/src/img/tem8.png",
                            Name = "CreativeAgency",
                            Price = 139m,
                            Tags = "creative, agency, website"
                        },
                        new
                        {
                            Id = 9,
                            Author = "PixelGenius",
                            AuthorId = 6,
                            Category = "Portfolio Design",
                            CategoryType = 5,
                            Description = "Professional Portfolio template that helps creative professionals showcase their work in the most compelling and organized way possible. This elegant design focuses on visual storytelling with large image galleries, smooth transitions, and intuitive navigation that guides visitors through your creative journey. The customizable sections allow you to highlight different types of work, from graphic design and photography to web development and branding projects. Built with SEO optimization and social media integration to help you reach a wider audience and attract new opportunities.",
                            Downloads = 900,
                            ImageUrl = "~/src/img/tem9.png",
                            Name = "PortfolioPro",
                            Price = 79m,
                            Tags = "portfolio, professional, design"
                        },
                        new
                        {
                            Id = 10,
                            Author = "DesignVista",
                            AuthorId = 1,
                            Category = "Portfolio Design",
                            CategoryType = 5,
                            Description = "Creative Design Portfolio that celebrates artistic expression and showcases your unique creative vision with a modern, minimalist approach. This template emphasizes visual impact with full-screen galleries, custom animations, and typography that complements your work without overwhelming it. The flexible layout system allows you to create custom presentations for different types of projects, from branding campaigns to digital illustrations and user interface designs. Perfect for designers, illustrators, and creative professionals who want their work to speak for itself.",
                            Downloads = 800,
                            ImageUrl = "~/src/img/tem10.png",
                            Name = "DesignPortfolio",
                            Price = 69m,
                            Tags = "design, portfolio, creative"
                        },
                        new
                        {
                            Id = 11,
                            Author = "TemplatePro",
                            AuthorId = 8,
                            Category = "Ecommerce",
                            CategoryType = 6,
                            Description = "E-commerce Store Platform that provides everything you need to launch and grow your online business with a professional, conversion-optimized design. This comprehensive template includes product catalogs, shopping cart functionality, secure checkout processes, and inventory management tools to streamline your e-commerce operations. The mobile-responsive design ensures customers can shop easily on any device, while the integrated payment gateways and shipping calculators provide a seamless purchasing experience. Built with performance and security in mind to handle high traffic and protect customer data.",
                            Downloads = 700,
                            ImageUrl = "~/src/img/tem11.png",
                            Name = "EcomStore",
                            Price = 189m,
                            Tags = "ecommerce, store, platform"
                        },
                        new
                        {
                            Id = 12,
                            Author = "WebStudio",
                            AuthorId = 9,
                            Category = "Ecommerce",
                            CategoryType = 6,
                            Description = "Professional Shopping Site that combines elegant design with powerful e-commerce functionality to create an exceptional online shopping experience. This feature-rich template includes advanced product filtering, wishlist functionality, customer reviews, and personalized recommendations to increase sales and customer satisfaction. The integrated analytics dashboard helps you track performance metrics and optimize your store for better conversions. Perfect for fashion retailers, electronics stores, and specialty shops looking to create a premium shopping experience that builds customer loyalty.",
                            Downloads = 600,
                            ImageUrl = "~/src/img/tem12.png",
                            Name = "ShopPro",
                            Price = 169m,
                            Tags = "shop, professional, ecommerce"
                        },
                        new
                        {
                            Id = 13,
                            Author = "DesignVista",
                            AuthorId = 1,
                            Category = "Education",
                            CategoryType = 7,
                            Description = "Educational Platform designed to facilitate online learning and knowledge sharing with an intuitive, student-friendly interface. This comprehensive template includes course catalogs, video streaming capabilities, interactive quizzes, and progress tracking tools to create engaging learning experiences. The integrated discussion forums and messaging systems foster collaboration between students and instructors, while the analytics dashboard helps educators monitor student progress and course effectiveness. Built for universities, training centers, and online education providers who want to deliver high-quality learning experiences.",
                            Downloads = 550,
                            ImageUrl = "~/src/img/tem1.png",
                            Name = "EduPlatform",
                            Price = 119m,
                            Tags = "education, platform, learning"
                        },
                        new
                        {
                            Id = 14,
                            Author = "DesignCraft",
                            AuthorId = 2,
                            Category = "Education",
                            CategoryType = 7,
                            Description = "Learning Management System that streamlines educational administration and enhances the learning experience for both students and instructors. This powerful template provides comprehensive tools for course creation, student enrollment, assignment management, and grade tracking in a user-friendly interface. The platform supports various content types including videos, documents, and interactive materials, while the built-in communication tools facilitate effective teacher-student interaction. Ideal for schools, corporate training programs, and educational institutions looking to modernize their learning delivery methods.",
                            Downloads = 480,
                            ImageUrl = "~/src/img/tem2.png",
                            Name = "LearnHub",
                            Price = 109m,
                            Tags = "learning, management, system"
                        },
                        new
                        {
                            Id = 15,
                            Author = "CodeMaven",
                            AuthorId = 3,
                            Category = "Health",
                            CategoryType = 8,
                            Description = "Healthcare Platform that provides a secure, user-friendly interface for medical professionals and patients to manage healthcare services efficiently. This HIPAA-compliant template includes patient portals, appointment scheduling systems, medical record management, and telemedicine capabilities to support modern healthcare delivery. The platform prioritizes data security and privacy while offering intuitive navigation for users of all technical levels. Built for hospitals, clinics, and healthcare providers who want to digitize their services and improve patient care through technology.",
                            Downloads = 420,
                            ImageUrl = "~/src/img/tem3.png",
                            Name = "HealthCare",
                            Price = 159m,
                            Tags = "health, care, platform"
                        },
                        new
                        {
                            Id = 16,
                            Author = "WebMaster",
                            AuthorId = 4,
                            Category = "Health",
                            CategoryType = 8,
                            Description = "Medical Services Website that establishes trust and credibility while providing essential information and services to patients and healthcare seekers. This professional template features doctor profiles, service descriptions, appointment booking systems, and educational content to help patients make informed healthcare decisions. The clean, reassuring design creates a calming environment that reduces patient anxiety while maintaining professional medical standards. Perfect for medical practices, dental offices, and healthcare facilities looking to build strong patient relationships and improve service accessibility.",
                            Downloads = 380,
                            ImageUrl = "~/src/img/tem4.png",
                            Name = "MedicalHub",
                            Price = 149m,
                            Tags = "medical, services, health"
                        },
                        new
                        {
                            Id = 17,
                            Author = "ThemeWiz",
                            AuthorId = 5,
                            Category = "Marketing",
                            CategoryType = 9,
                            Description = "Marketing Agency Platform that demonstrates your marketing expertise and attracts clients with compelling case studies and results-driven content. This conversion-focused template includes lead generation forms, client testimonials, service showcases, and ROI tracking tools to prove your marketing effectiveness. The integrated analytics and reporting features help you demonstrate value to clients while the blog and content marketing tools establish your agency as an industry thought leader. Built for marketing agencies, digital consultancies, and growth hackers who want to showcase their results and attract high-value clients.",
                            Downloads = 350,
                            ImageUrl = "~/src/img/tem5.png",
                            Name = "MarketingPro",
                            Price = 139m,
                            Tags = "marketing, agency, platform"
                        },
                        new
                        {
                            Id = 18,
                            Author = "PixelGenius",
                            AuthorId = 6,
                            Category = "Marketing",
                            CategoryType = 9,
                            Description = "Advertising Campaign Site that creates buzz and generates excitement around your products, services, or events with compelling storytelling and interactive elements. This dynamic template features countdown timers, social media integration, viral sharing tools, and conversion optimization features to maximize campaign effectiveness. The mobile-first design ensures your campaigns reach audiences wherever they are, while the integrated analytics help you track performance and optimize results in real-time. Perfect for product launches, event promotions, and brand awareness campaigns that need to make a big impact.",
                            Downloads = 320,
                            ImageUrl = "~/src/img/tem6.png",
                            Name = "AdCampaign",
                            Price = 129m,
                            Tags = "advertising, campaign, marketing"
                        },
                        new
                        {
                            Id = 19,
                            Author = "WebMajestic",
                            AuthorId = 7,
                            Category = "Restaurant & Food",
                            CategoryType = 10,
                            Description = "Restaurant Management Platform that streamlines operations and enhances customer experience with online ordering, table reservations, and inventory management tools. This comprehensive template includes menu management, order tracking, customer feedback systems, and loyalty programs to help restaurants increase sales and build customer relationships. The mobile-responsive design ensures customers can easily browse menus, place orders, and make reservations from any device. Built for restaurants, cafes, and food service businesses looking to modernize their operations and improve customer satisfaction.",
                            Downloads = 290,
                            ImageUrl = "~/src/img/tem7.png",
                            Name = "RestaurantHub",
                            Price = 119m,
                            Tags = "restaurant, food, management"
                        },
                        new
                        {
                            Id = 20,
                            Author = "TemplatePro",
                            AuthorId = 8,
                            Category = "Restaurant & Food",
                            CategoryType = 10,
                            Description = "Food Delivery Service platform that connects restaurants with customers through an intuitive ordering system and real-time delivery tracking. This feature-rich template includes restaurant listings, menu browsing, secure payment processing, and delivery status updates to create a seamless food ordering experience. The integrated driver management system and route optimization tools help ensure timely deliveries while the customer review system builds trust and helps restaurants improve their service. Perfect for food delivery startups, restaurant chains, and meal kit services looking to expand their digital presence.",
                            Downloads = 260,
                            ImageUrl = "~/src/img/tem8.png",
                            Name = "FoodDelivery",
                            Price = 109m,
                            Tags = "food, delivery, service"
                        },
                        new
                        {
                            Id = 21,
                            Author = "PixelGenius",
                            AuthorId = 6,
                            Category = "Gaming & Entertainment",
                            CategoryType = 11,
                            Description = "Gaming Studio Platform that showcases your games and connects with players through an immersive, gaming-focused design that reflects the excitement of interactive entertainment. This dynamic template includes game galleries, development blogs, community forums, and player feedback systems to build a strong gaming community around your studio. The integrated streaming capabilities and social media features help promote your games and engage with players across multiple platforms. Built for indie game developers, gaming studios, and esports organizations looking to build passionate player communities.",
                            Downloads = 240,
                            ImageUrl = "~/src/img/tem9.png",
                            Name = "GameStudio",
                            Price = 169m,
                            Tags = "gaming, studio, platform"
                        },
                        new
                        {
                            Id = 22,
                            Author = "DesignVista",
                            AuthorId = 1,
                            Category = "Gaming & Entertainment",
                            CategoryType = 11,
                            Description = "Entertainment Website that captivates audiences with stunning visuals, engaging content, and interactive features that bring entertainment to life online. This multimedia-rich template includes video streaming capabilities, event calendars, artist profiles, and fan interaction tools to create immersive entertainment experiences. The responsive design ensures optimal viewing across all devices while the integrated social features help build fan communities and increase engagement. Perfect for entertainment companies, streaming platforms, and content creators looking to deliver compelling digital experiences.",
                            Downloads = 220,
                            ImageUrl = "~/src/img/tem10.png",
                            Name = "EntertainmentHub",
                            Price = 159m,
                            Tags = "entertainment, gaming, website"
                        },
                        new
                        {
                            Id = 23,
                            Author = "TemplatePro",
                            AuthorId = 8,
                            Category = "Real Estate",
                            CategoryType = 12,
                            Description = "Real Estate Platform that helps agents and agencies showcase properties effectively and connect with potential buyers through comprehensive listing management and search tools. This professional template includes property galleries, virtual tour capabilities, mortgage calculators, and client relationship management features to streamline the real estate process. The advanced search and filtering options help buyers find their perfect property while the integrated lead generation tools help agents convert visitors into clients. Built for real estate agencies, property developers, and individual agents looking to modernize their business.",
                            Downloads = 200,
                            ImageUrl = "~/src/img/tem11.png",
                            Name = "RealEstatePro",
                            Price = 179m,
                            Tags = "real estate, property, platform"
                        },
                        new
                        {
                            Id = 24,
                            Author = "WebStudio",
                            AuthorId = 9,
                            Category = "Real Estate",
                            CategoryType = 12,
                            Description = "Property Management System that simplifies property administration and tenant communication through an integrated platform designed for property managers and landlords. This comprehensive template includes tenant portals, maintenance request systems, rent collection tools, and property analytics to help manage real estate investments efficiently. The secure messaging system and document management features facilitate clear communication between property managers and tenants while the financial tracking tools help monitor property performance. Perfect for property management companies, real estate investors, and landlords looking to streamline their operations.",
                            Downloads = 180,
                            ImageUrl = "~/src/img/tem12.png",
                            Name = "PropertyHub",
                            Price = 169m,
                            Tags = "property, management, real estate"
                        });
                });

            modelBuilder.Entity("Templify.Domain.Entities.TemplateSub", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AppUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.HasIndex("ProductId");

                    b.ToTable("TemplateSubs");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Templify.Domain.Entities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Templify.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Templify.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Templify.Domain.Entities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Templify.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Templify.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Templify.Domain.Entities.AppUser", b =>
                {
                    b.HasOne("Templify.Domain.Entities.ApplicationUser", "Identity")
                        .WithOne("AppUser")
                        .HasForeignKey("Templify.Domain.Entities.AppUser", "IdentityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Identity");
                });

            modelBuilder.Entity("Templify.Domain.Entities.Product", b =>
                {
                    b.HasOne("Templify.Domain.Entities.Author", "AuthorEntity")
                        .WithMany("Products")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AuthorEntity");
                });

            modelBuilder.Entity("Templify.Domain.Entities.TemplateSub", b =>
                {
                    b.HasOne("Templify.Domain.Entities.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Templify.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Templify.Domain.Entities.ApplicationUser", b =>
                {
                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("Templify.Domain.Entities.Author", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
